const continents = [
    {
        name: 'Africa',
        code: '002',
    },
    {
        name: 'Americas',
        code: '019',
    },
    {
        name: 'Antarctica',
        code: '010',
    },
    {
        name: 'Asia',
        code: '142',
    },
    {
        name: 'Europe',
        code: '150',
    },
    {
        name: 'Oceania',
        code: '009',
    },
];

const regions1 = [
    {
        name: 'Northern Africa',
        code: '015',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Sub-Saharan Africa',
        code: '202',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Latin America and the Caribbean',
        code: '419',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Northern America',
        code: '021',
        continentCode: '019',
        Continent: 'Americas',
    },
    {
        name: 'Central Asia',
        code: '143',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Eastern Asia',
        code: '030',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'South-eastern Asia',
        code: '035',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Southern Asia',
        code: '034',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Western Asia',
        code: '145',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Eastern Europe',
        code: '151',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Southern Europe',
        code: '039',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Western Europe',
        code: '155',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Australia and New Zealand',
        code: '053',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Melanesia',
        code: '054',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Micronesia',
        code: '057',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Polynesia',
        code: '061',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Northern Europe',
        code: '154',
        continentCode: '150',
        continent: 'Europe',
    },
];

const regions2 = [
    {
        name: 'Eastern Africa',
        code: '014',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Middle Africa',
        code: '017',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Southern Africa',
        code: '018',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Western Africa',
        code: '011',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Caribbean',
        code: '029',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Central America',
        code: '013',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'South America',
        code: '005',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Channel Islands',
        code: '830',
        region1Code: '154',
        region1: 'Northern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
];

const countries = [
    {
        name: 'Afghanistan',
        alpha2: 'AF',
        alpha3: 'AFG',
        countryCode: '004',
        region1Code: '034',
        region1: 'Southern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Åland Islands',
        alpha2: 'AX',
        alpha3: 'ALA',
        countryCode: 248,
        region1Code: '154',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Albania',
        alpha2: 'AL',
        alpha3: 'ALB',
        countryCode: '008',
        region: 'Europe',
        region1Code: '039',
        region1: 'Southern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Algeria',
        alpha2: 'DZ',
        alpha3: 'DZA',
        countryCode: '012',
        region: 'Africa',
        region1: 'Northern Africa',
        region1Code: '015',
        continentCode: '002',
        continent: 'Africa',
    },
    {
        name: 'American Samoa',
        alpha2: 'AS',
        alpha3: 'ASM',
        countryCode: '016',
        region: 'Oceania',
        region1Code: '061',
        region1: 'Polynesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Andorra',
        alpha2: 'AD',
        alpha3: 'AND',
        countryCode: '020',
        region: 'Europe',
        region1Code: '039',
        region1: 'Southern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Angola',
        alpha2: 'AO',
        alpha3: 'AGO',
        countryCode: '024',
        region: 'Africa',
        region2Code: '017',
        region2: 'Middle Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Anguilla',
        alpha2: 'AI',
        alpha3: 'AIA',
        countryCode: 660,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Antarctica',
        alpha2: 'AQ',
        alpha3: 'ATA',
        countryCode: '010',
        continentCode: '010',
        continent: 'Antarctica',
    },
    {
        name: 'Antigua and Barbuda',
        alpha2: 'AG',
        alpha3: 'ATG',
        countryCode: '028',
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Argentina',
        alpha2: 'AR',
        alpha3: 'ARG',
        countryCode: '032',
        region: 'Americas',
        region2Code: '005',
        region2: 'South America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Armenia',
        alpha2: 'AM',
        alpha3: 'ARM',
        countryCode: '051',
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Aruba',
        alpha2: 'AW',
        alpha3: 'ABW',
        countryCode: 533,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Australia',
        alpha2: 'AU',
        alpha3: 'AUS',
        countryCode: '036',
        region: 'Oceania',
        region1Code: '053',
        region1: 'Australia and New Zealand',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Austria',
        alpha2: 'AT',
        alpha3: 'AUT',
        countryCode: '040',
        region: 'Europe',
        region1Code: '155',
        region1: 'Western Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Azerbaijan',
        alpha2: 'AZ',
        alpha3: 'AZE',
        countryCode: '031',
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Bahamas',
        alpha2: 'BS',
        alpha3: 'BHS',
        countryCode: '044',
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Bahrain',
        alpha2: 'BH',
        alpha3: 'BHR',
        countryCode: '048',
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Bangladesh',
        alpha2: 'BD',
        alpha3: 'BGD',
        countryCode: '050',
        region: 'Asia',
        region1Code: '034',
        region1: 'Southern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Barbados',
        alpha2: 'BB',
        alpha3: 'BRB',
        countryCode: '052',
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Belarus',
        alpha2: 'BY',
        alpha3: 'BLR',
        countryCode: 112,
        region: 'Europe',
        region1Code: '151',
        region1: 'Eastern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Belgium',
        alpha2: 'BE',
        alpha3: 'BEL',
        countryCode: '056',
        region: 'Europe',
        region1Code: '155',
        region1: 'Western Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Belize',
        alpha2: 'BZ',
        alpha3: 'BLZ',
        countryCode: '084',
        region: 'Americas',
        region2Code: '013',
        region2: 'Central America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Benin',
        alpha2: 'BJ',
        alpha3: 'BEN',
        region2Code: '011',
        region2: 'Western Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Bermuda',
        alpha2: 'BM',
        alpha3: 'BMU',
        countryCode: '060',
        region: 'Americas',
        region1Code: '021',
        region1: 'Northern America',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Bhutan',
        alpha2: 'BT',
        alpha3: 'BTN',
        countryCode: '064',
        region: 'Asia',
        region1Code: '034',
        region1: 'Southern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Bolivia',
        alpha2: 'BO',
        alpha3: 'BOL',
        alternativeNames: ['Plurinational State of'],
        countryCode: '068',
        region: 'Americas',
        region2Code: '005',
        region2: 'South America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Caribbean Netherlands',
        alpha2: 'BQ',
        alpha3: 'BES',
        alternativeNames: ['Bonaire', ' Sint Eustatius and Saba'],
        countryCode: 535,
        region: 'Americas',
        region1Code: '155',
        region1: 'Western Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Bosnia and Herzegovina',
        alpha2: 'BA',
        alpha3: 'BIH',
        countryCode: '070',
        region: 'Europe',
        region1Code: '039',
        region1: 'Southern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Botswana',
        alpha2: 'BW',
        alpha3: 'BWA',
        countryCode: '072',
        region: 'Africa',
        region2Code: '018',
        region2: 'Southern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Bouvet Island',
        alpha2: 'BV',
        alpha3: 'BVT',
        countryCode: '074',
        region: 'Americas',
        region2Code: '005',
        region2: 'South America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Brazil',
        alpha2: 'BR',
        alpha3: 'BRA',
        countryCode: '076',
        region: 'Americas',
        region2Code: '005',
        region2: 'South America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'British Indian Ocean Territory',
        alpha2: 'IO',
        alpha3: 'IOT',
        countryCode: '086',
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Brunei Darussalam',
        alpha2: 'BN',
        alpha3: 'BRN',
        countryCode: '096',
        region: 'Asia',
        region1Code: '035',
        region1: 'South-eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Bulgaria',
        alpha2: 'BG',
        alpha3: 'BGR',
        countryCode: 100,
        region: 'Europe',
        region1Code: '151',
        region1: 'Eastern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Burkina Faso',
        alpha2: 'BF',
        alpha3: 'BFA',
        countryCode: 854,
        region: 'Africa',
        region2Code: '011',
        region2: 'Western Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Burundi',
        alpha2: 'BI',
        alpha3: 'BDI',
        countryCode: 108,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Cabo Verde',
        alpha2: 'CV',
        alpha3: 'CPV',
        countryCode: 132,
        region: 'Africa',
        region2Code: '011',
        region2: 'Western Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Cambodia',
        alpha2: 'KH',
        alpha3: 'KHM',
        countryCode: 116,
        region: 'Asia',
        region1Code: '035',
        region1: 'South-eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Cameroon',
        alpha2: 'CM',
        alpha3: 'CMR',
        countryCode: 120,
        region: 'Africa',
        region2Code: '017',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Canada',
        alpha2: 'CA',
        alpha3: 'CAN',
        countryCode: 124,
        region: 'Americas',
        region1Code: '021',
        region1: 'Northern America',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Cayman Islands',
        alpha2: 'KY',
        alpha3: 'CYM',
        countryCode: 136,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Central African Republic',
        alpha2: 'CF',
        alpha3: 'CAF',
        countryCode: 140,
        region: 'Africa',
        region2Code: '017',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Chad',
        alpha2: 'TD',
        alpha3: 'TCD',
        countryCode: 148,
        region: 'Africa',
        region2Code: '017',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Chile',
        alpha2: 'CL',
        alpha3: 'CHL',
        countryCode: 152,
        region: 'Americas',
        region2Code: '005',
        region2: 'South America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'China',
        alpha2: 'CN',
        alpha3: 'CHN',
        countryCode: 156,
        region: 'Asia',
        region1Code: '030',
        region1: 'Eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Christmas Island',
        alpha2: 'CX',
        alpha3: 'CXR',
        countryCode: 162,
        region: 'Oceania',
        region1Code: '053',
        region1: 'Australia and New Zealand',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Cocos Islands',
        alpha2: 'CC',
        alpha3: 'CCK',
        alternativeNames: ['Cocos (Keeling) Islands'],
        countryCode: 166,
        region: 'Oceania',
        region1Code: '053',
        region1: 'Australia and New Zealand',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Colombia',
        alpha2: 'CO',
        alpha3: 'COL',
        countryCode: 170,
        region: 'Americas',
        region2Code: '005',
        region2: 'South America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Comoros',
        alpha2: 'KM',
        alpha3: 'COM',
        countryCode: 174,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Congo',
        alpha2: 'CG',
        alpha3: 'COG',
        alternativeNames: ['Congo, Democratic Republic of the'],
        countryCode: 178,
        region: 'Africa',
        region2Code: '017',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Congo',
        alpha2: 'CD',
        alpha3: 'COD',
        countryCode: 180,
        region: 'Africa',
        region2Code: '017',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Cook Islands',
        alpha2: 'CK',
        alpha3: 'COK',
        countryCode: 184,
        region: 'Oceania',
        region1Code: '061',
        region1: 'Polynesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Costa Rica',
        alpha2: 'CR',
        alpha3: 'CRI',
        countryCode: 188,
        region: 'Americas',
        region2Code: '013',
        region2: 'Central America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: "Côte d'Ivoire",
        alpha2: 'CI',
        alpha3: 'CIV',
        countryCode: 384,
        region: 'Africa',
        region2Code: '011',
        region2: 'Western Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Croatia',
        alpha2: 'HR',
        alpha3: 'HRV',
        countryCode: 191,
        region: 'Europe',
        region1Code: '039',
        region1: 'Southern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Cuba',
        alpha2: 'CU',
        alpha3: 'CUB',
        countryCode: 192,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Curaçao',
        alpha2: 'CW',
        alpha3: 'CUW',
        countryCode: 531,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Cyprus',
        alpha2: 'CY',
        alpha3: 'CYP',
        countryCode: 196,
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Czechia',
        alpha2: 'CZ',
        alpha3: 'CZE',
        countryCode: 203,
        region: 'Europe',
        region1Code: '151',
        region1: 'Eastern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Denmark',
        alpha2: 'DK',
        alpha3: 'DNK',
        countryCode: 208,
        region: 'Europe',
        region1Code: '154',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Djibouti',
        alpha2: 'DJ',
        alpha3: 'DJI',
        countryCode: 262,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Dominica',
        alpha2: 'DM',
        alpha3: 'DMA',
        countryCode: 212,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Dominican Republic',
        alpha2: 'DO',
        alpha3: 'DOM',
        countryCode: 214,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Ecuador',
        alpha2: 'EC',
        alpha3: 'ECU',
        countryCode: 218,
        region: 'Americas',
        region2Code: '005',
        region2: 'South America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Egypt',
        alpha2: 'EG',
        alpha3: 'EGY',
        countryCode: 818,
        region: 'Africa',
        region1Code: '015',
        region1: 'Northern Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'El Salvador',
        alpha2: 'SV',
        alpha3: 'SLV',
        countryCode: 222,
        region: 'Americas',
        region2Code: '013',
        region2: 'Central America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Equatorial Guinea',
        alpha2: 'GQ',
        alpha3: 'GNQ',
        countryCode: 226,
        region: 'Africa',
        region2Code: '017',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Eritrea',
        alpha2: 'ER',
        alpha3: 'ERI',
        countryCode: 232,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Estonia',
        alpha2: 'EE',
        alpha3: 'EST',
        countryCode: 233,
        region: 'Europe',
        region1Code: '154',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Eswatini',
        alpha2: 'SZ',
        alpha3: 'SWZ',
        countryCode: 748,
        region: 'Africa',
        region2Code: '018',
        region2: 'Southern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Ethiopia',
        alpha2: 'ET',
        alpha3: 'ETH',
        countryCode: 231,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Falkland Islands (Malvinas)',
        alpha2: 'FK',
        alpha3: 'FLK',
        countryCode: 238,
        region: 'Americas',
        region2Code: '005',
        region2: 'South America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Faroe Islands',
        alpha2: 'FO',
        alpha3: 'FRO',
        countryCode: 234,
        region: 'Europe',
        region1Code: '154',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Fiji',
        alpha2: 'FJ',
        alpha3: 'FJI',
        countryCode: 242,
        region: 'Oceania',
        region1Code: '054',
        region1: 'Melanesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Finland',
        alpha2: 'FI',
        alpha3: 'FIN',
        countryCode: 246,
        region: 'Europe',
        region1Code: '154',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'France',
        alpha2: 'FR',
        alpha3: 'FRA',
        countryCode: 250,
        region: 'Europe',
        region1Code: '155',
        region1: 'Western Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'French Guiana',
        alpha2: 'GF',
        alpha3: 'GUF',
        countryCode: 254,
        region: 'Americas',
        region2Code: '005',
        region2: 'South America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'French Polynesia',
        alpha2: 'PF',
        alpha3: 'PYF',
        countryCode: 258,
        region: 'Oceania',
        region1Code: '061',
        region1: 'Polynesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'French Southern Territories',
        alpha2: 'TF',
        alpha3: 'ATF',
        countryCode: 260,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Gabon',
        alpha2: 'GA',
        alpha3: 'GAB',
        countryCode: 266,
        region: 'Africa',
        region2Code: '017',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Gambia',
        alpha2: 'GM',
        alpha3: 'GMB',
        countryCode: 270,
        region: 'Africa',
        region2Code: '011',
        region2: 'Western Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Georgia',
        alpha2: 'GE',
        alpha3: 'GEO',
        countryCode: 268,
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Germany',
        alpha2: 'DE',
        alpha3: 'DEU',
        countryCode: 276,
        region: 'Europe',
        region1Code: '155',
        region1: 'Western Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Ghana',
        alpha2: 'GH',
        alpha3: 'GHA',
        countryCode: 288,
        region: 'Africa',
        region2Code: '011',
        region2: 'Western Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Gibraltar',
        alpha2: 'GI',
        alpha3: 'GIB',
        countryCode: 292,
        region: 'Europe',
        region1Code: '039',
        region1: 'Southern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Greece',
        alpha2: 'GR',
        alpha3: 'GRC',
        countryCode: 300,
        region: 'Europe',
        region1Code: '039',
        region1: 'Southern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Greenland',
        alpha2: 'GL',
        alpha3: 'GRL',
        countryCode: 304,
        region: 'Americas',
        region1Code: '021',
        region1: 'Northern America',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Grenada',
        alpha2: 'GD',
        alpha3: 'GRD',
        countryCode: 308,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Guadeloupe',
        alpha2: 'GP',
        alpha3: 'GLP',
        countryCode: 312,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Guam',
        alpha2: 'GU',
        alpha3: 'GUM',
        countryCode: 316,
        region: 'Oceania',
        region1Code: '057',
        region1: 'Micronesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Guatemala',
        alpha2: 'GT',
        alpha3: 'GTM',
        countryCode: 320,
        region: 'Americas',
        region2Code: '013',
        region2: 'Central America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Guernsey',
        alpha2: 'GG',
        alpha3: 'GGY',
        countryCode: 831,
        region: 'Europe',
        region2Code: '830',
        region2: 'Channel Islands',
        region1Code: '154',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Guinea',
        alpha2: 'GN',
        alpha3: 'GIN',
        countryCode: 324,
        region: 'Africa',
        region2Code: '011',
        region2: 'Western Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Guinea-Bissau',
        alpha2: 'GW',
        alpha3: 'GNB',
        countryCode: 624,
        region: 'Africa',
        region2Code: '011',
        region2: 'Western Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Guyana',
        alpha2: 'GY',
        alpha3: 'GUY',
        countryCode: 328,
        region: 'Americas',
        region2Code: '005',
        region2: 'South America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Haiti',
        alpha2: 'HT',
        alpha3: 'HTI',
        countryCode: 332,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Heard Island and McDonald Islands',
        alpha2: 'HM',
        alpha3: 'HMD',
        countryCode: 334,
        region: 'Oceania',
        region1Code: '053',
        region1: 'Australia and New Zealand',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Holy See',
        alpha2: 'VA',
        alpha3: 'VAT',
        countryCode: 336,
        region: 'Europe',
        region1Code: '039',
        region1: 'Southern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Honduras',
        alpha2: 'HN',
        alpha3: 'HND',
        countryCode: 340,
        region: 'Americas',
        region2Code: '013',
        region2: 'Central America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Hong Kong',
        alpha2: 'HK',
        alpha3: 'HKG',
        countryCode: 344,
        region: 'Asia',
        region1Code: '030',
        region1: 'Eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Hungary',
        alpha2: 'HU',
        alpha3: 'HUN',
        countryCode: 348,
        region: 'Europe',
        region1Code: '151',
        region1: 'Eastern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Iceland',
        alpha2: 'IS',
        alpha3: 'ISL',
        countryCode: 352,
        region: 'Europe',
        region1Code: '154',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'India',
        alpha2: 'IN',
        alpha3: 'IND',
        countryCode: 356,
        region: 'Asia',
        region1Code: '034',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Indonesia',
        alpha2: 'ID',
        alpha3: 'IDN',
        countryCode: 360,
        region: 'Asia',
        region1Code: '035',
        region1: 'South-eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Iran',
        alpha2: 'IR',
        alpha3: 'IRN',
        alternativeNames: ['Iran (Islamic Republic of)'],
        countryCode: 364,
        region: 'Asia',
        region1Code: '034',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Iraq',
        alpha2: 'IQ',
        alpha3: 'IRQ',
        countryCode: 368,
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Ireland',
        alpha2: 'IE',
        alpha3: 'IRL',
        countryCode: 372,
        region: 'Europe',
        region1Code: '154',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Isle of Man',
        alpha2: 'IM',
        alpha3: 'IMN',
        countryCode: 833,
        region: 'Europe',
        region1Code: '154',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Israel',
        alpha2: 'IL',
        alpha3: 'ISR',
        countryCode: 376,
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Italy',
        alpha2: 'IT',
        alpha3: 'ITA',
        countryCode: 380,
        region: 'Europe',
        region1Code: '039',
        region1: 'Southern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Jamaica',
        alpha2: 'JM',
        alpha3: 'JAM',
        countryCode: 388,
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Japan',
        alpha2: 'JP',
        alpha3: 'JPN',
        countryCode: 392,
        region: 'Asia',
        region1Code: '030',
        region1: 'Eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Jersey',
        alpha2: 'JE',
        alpha3: 'JEY',
        countryCode: 832,
        region: 'Europe',
        'region-code': 150,
        region1Code: '154',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Jordan',
        alpha2: 'JO',
        alpha3: 'JOR',
        countryCode: 400,
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Kazakhstan',
        alpha2: 'KZ',
        alpha3: 'KAZ',
        countryCode: 398,
        region: 'Asia',
        region1Code: '143',
        region1: 'Central Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Kenya',
        alpha2: 'KE',
        alpha3: 'KEN',
        countryCode: 404,
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Kiribati',
        alpha2: 'KI',
        alpha3: 'KIR',
        countryCode: 296,
        region: 'Oceania',
        region1Code: '057',
        region1: 'Micronesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'North Korea',
        alpha2: 'KP',
        alpha3: 'PRK',
        alternativeNames: ["Korea (Democratic People's Republic of)"],
        countryCode: 408,
        region: 'Asia',
        region1Code: '030',
        region1: 'Eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'South Korea',
        alpha2: 'KR',
        alpha3: 'KOR',
        alternativeNames: ['Korea, Republic of'],
        countryCode: 410,
        region: 'Asia',
        region1Code: '030',
        region1: 'Eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Kuwait',
        alpha2: 'KW',
        alpha3: 'KWT',
        countryCode: 414,
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Kyrgyzstan',
        alpha2: 'KG',
        alpha3: 'KGZ',
        countryCode: 417,
        region: 'Asia',
        region1Code: '143',
        region1: 'Central Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Lao',
        alpha2: 'LA',
        alpha3: 'LAO',
        alternativeNames: ["Lao People's Democratic Republic"],
        countryCode: 418,
        region: 'Asia',
        region1Code: '035',
        region1: 'South-eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Latvia',
        alpha2: 'LV',
        alpha3: 'LVA',
        countryCode: 428,
        region: 'Europe',
        region1Code: '154',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Lebanon',
        alpha2: 'LB',
        alpha3: 'LBN',
        countryCode: 422,
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Lesotho',
        alpha2: 'LS',
        alpha3: 'LSO',
        countryCode: 426,
        region2Code: '018',
        region2: 'Southern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Liberia',
        alpha2: 'LR',
        alpha3: 'LBR',
        countryCode: 430,
        region: 'Africa',
        region2Code: '011',
        region2: 'Western Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Libya',
        alpha2: 'LY',
        alpha3: 'LBY',
        countryCode: 434,
        region: 'Africa',
        region1Code: '015',
        region1: 'Northern Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Liechtenstein',
        alpha2: 'LI',
        alpha3: 'LIE',
        countryCode: 438,
        region: 'Europe',
        region1Code: '155',
        region1: 'Western Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Lithuania',
        alpha2: 'LT',
        alpha3: 'LTU',
        countryCode: 440,
        region: 'Europe',
        region1Code: '154',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Luxembourg',
        alpha2: 'LU',
        alpha3: 'LUX',
        countryCode: 442,
        region: 'Europe',
        region1Code: '155',
        region1: 'Western Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Macao',
        alpha2: 'MO',
        alpha3: 'MAC',
        countryCode: 446,
        region: 'Asia',
        region1Code: '030',
        region1: 'Eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Madagascar',
        alpha2: 'MG',
        alpha3: 'MDG',
        countryCode: 450,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Malawi',
        alpha2: 'MW',
        alpha3: 'MWI',
        countryCode: 454,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Malaysia',
        alpha2: 'MY',
        alpha3: 'MYS',
        countryCode: 458,
        region: 'Asia',
        region1Code: '035',
        region1: 'South-eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Maldives',
        alpha2: 'MV',
        alpha3: 'MDV',
        countryCode: 462,
        region: 'Asia',
        region1Code: '034',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Mali',
        alpha2: 'ML',
        alpha3: 'MLI',
        countryCode: 466,
        region: 'Africa',
        region2Code: '011',
        region2: 'Western Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Malta',
        alpha2: 'MT',
        alpha3: 'MLT',
        countryCode: 470,
        region: 'Europe',
        region1Code: '039',
        region1: 'Southern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Marshall Islands',
        alpha2: 'MH',
        alpha3: 'MHL',
        countryCode: 584,
        region: 'Oceania',
        region1Code: '057',
        region1: 'Micronesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Martinique',
        alpha2: 'MQ',
        alpha3: 'MTQ',
        countryCode: 474,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Mauritania',
        alpha2: 'MR',
        alpha3: 'MRT',
        countryCode: 478,
        region: 'Africa',
        region2Code: '011',
        region2: 'Western Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Mauritius',
        alpha2: 'MU',
        alpha3: 'MUS',
        countryCode: 480,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Mayotte',
        alpha2: 'YT',
        alpha3: 'MYT',
        countryCode: 175,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Mexico',
        alpha2: 'MX',
        alpha3: 'MEX',
        countryCode: 484,
        region: 'Americas',
        region2Code: '013',
        region2: 'Central America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Federated States of Micronesia',
        alpha2: 'FM',
        alpha3: 'FSM',
        alternativeNames: ['Micronesia', 'Federated States'],
        countryCode: 583,
        region: 'Oceania',
        region1Code: '057',
        region1: 'Micronesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Moldova',
        alpha2: 'MD',
        alpha3: 'MDA',
        alternativeNames: ['Moldova, Republic of'],
        countryCode: 498,
        region: 'Europe',
        region1Code: '151',
        region1: 'Eastern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Monaco',
        alpha2: 'MC',
        alpha3: 'MCO',
        countryCode: 492,
        region: 'Europe',
        region1Code: '155',
        region1: 'Western Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Mongolia',
        alpha2: 'MN',
        alpha3: 'MNG',
        countryCode: 496,
        region: 'Asia',
        region1Code: '030',
        region1: 'Eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Montenegro',
        alpha2: 'ME',
        alpha3: 'MNE',
        countryCode: 499,
        region: 'Europe',
        region1Code: '039',
        region1: 'Southern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Montserrat',
        alpha2: 'MS',
        alpha3: 'MSR',
        countryCode: 500,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Morocco',
        alternativeNames: ['Maghrib', 'Al maghrib'],
        alpha2: 'MA',
        alpha3: 'MAR',
        countryCode: 504,
        region: 'Africa',
        region1Code: '015',
        region1: 'Northern Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Mozambique',
        alpha2: 'MZ',
        alpha3: 'MOZ',
        countryCode: 508,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Myanmar',
        alpha2: 'MM',
        alpha3: 'MMR',
        countryCode: 104,
        region: 'Asia',
        region1Code: '035',
        region1: 'South-eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Namibia',
        alpha2: 'NA',
        alpha3: 'NAM',
        countryCode: 516,
        region: 'Africa',
        region2Code: '018',
        region2: 'Southern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Nauru',
        alpha2: 'NR',
        alpha3: 'NRU',
        countryCode: 520,
        region: 'Oceania',
        region1Code: '057',
        region1: 'Micronesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Nepal',
        alpha2: 'NP',
        alpha3: 'NPL',
        countryCode: 524,
        region: 'Asia',
        region1Code: '034',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Netherlands',
        alpha2: 'NL',
        alpha3: 'NLD',
        countryCode: 528,
        region: 'Europe',
        region1Code: '155',
        region1: 'Western Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'New Caledonia',
        alpha2: 'NC',
        alpha3: 'NCL',
        countryCode: 540,
        region: 'Oceania',
        region1Code: '054',
        region1: 'Melanesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'New Zealand',
        alpha2: 'NZ',
        alpha3: 'NZL',
        countryCode: 554,
        region: 'Oceania',
        region1Code: '053',
        region1: 'Australia and New Zealand',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Nicaragua',
        alpha2: 'NI',
        alpha3: 'NIC',
        countryCode: 558,
        region: 'Americas',
        region2Code: '013',
        region2: 'Central America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Niger',
        alpha2: 'NE',
        alpha3: 'NER',
        countryCode: 562,
        region: 'Africa',
        region2Code: '011',
        region2: 'Western Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Nigeria',
        alpha2: 'NG',
        alpha3: 'NGA',
        countryCode: 566,
        region: 'Africa',
        region2Code: '011',
        region2: 'Western Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Niue',
        alpha2: 'NU',
        alpha3: 'NIU',
        countryCode: 570,
        region: 'Oceania',
        region1Code: '061',
        region1: 'Polynesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Norfolk Island',
        alpha2: 'NF',
        alpha3: 'NFK',
        countryCode: 574,
        region: 'Oceania',
        region1Code: '053',
        region1: 'Australia and New Zealand',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'North Macedonia',
        alpha2: 'MK',
        alpha3: 'MKD',
        countryCode: 807,
        region: 'Europe',
        region1Code: '039',
        region1: 'Southern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Northern Mariana Islands',
        alpha2: 'MP',
        alpha3: 'MNP',
        countryCode: 580,
        region: 'Oceania',
        region1Code: '057',
        region1: 'Micronesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Norway',
        alpha2: 'NO',
        alpha3: 'NOR',
        countryCode: 578,
        region: 'Europe',
        region1Code: '154',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Oman',
        alpha2: 'OM',
        alpha3: 'OMN',
        countryCode: 512,
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Pakistan',
        alpha2: 'PK',
        alpha3: 'PAK',
        countryCode: 586,
        region: 'Asia',
        region1Code: '034',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Palau',
        alpha2: 'PW',
        alpha3: 'PLW',
        countryCode: 585,
        region: 'Oceania',
        region1Code: '057',
        region1: 'Micronesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Palestine',
        alpha2: 'PS',
        alpha3: 'PSE',
        alternativeNames: ['Palestine, State of'],
        countryCode: 275,
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Panama',
        alpha2: 'PA',
        alpha3: 'PAN',
        countryCode: 591,
        region: 'Americas',
        region2Code: '013',
        region2: 'Central America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Papua New Guinea',
        alpha2: 'PG',
        alpha3: 'PNG',
        countryCode: 598,
        region: 'Oceania',
        region1Code: '054',
        region1: 'Melanesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Paraguay',
        alpha2: 'PY',
        alpha3: 'PRY',
        countryCode: 600,
        region: 'Americas',
        region2Code: '005',
        region2: 'South America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Peru',
        alpha2: 'PE',
        alpha3: 'PER',
        countryCode: 604,
        region: 'Americas',
        region2Code: '005',
        region2: 'South America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Philippines',
        alpha2: 'PH',
        alpha3: 'PHL',
        countryCode: 608,
        region: 'Asia',
        region1Code: '035',
        region1: 'South-eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Pitcairn',
        alpha2: 'PN',
        alpha3: 'PCN',
        countryCode: 612,
        region: 'Oceania',
        region1Code: '061',
        region1: 'Polynesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Poland',
        alpha2: 'PL',
        alpha3: 'POL',
        countryCode: 616,
        region: 'Europe',
        region1Code: '151',
        region1: 'Eastern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Portugal',
        alpha2: 'PT',
        alpha3: 'PRT',
        countryCode: 620,
        region: 'Europe',
        region1Code: '039',
        region1: 'Southern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Puerto Rico',
        alpha2: 'PR',
        alpha3: 'PRI',
        countryCode: 630,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Qatar',
        alpha2: 'QA',
        alpha3: 'QAT',
        countryCode: 634,
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Réunion',
        alpha2: 'RE',
        alpha3: 'REU',
        countryCode: 638,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Romania',
        alpha2: 'RO',
        alpha3: 'ROU',
        countryCode: 642,
        region: 'Europe',
        region1Code: '151',
        region1: 'Eastern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Russia',
        alpha2: 'RU',
        alpha3: 'RUS',
        alternativeNames: ['Russian Federation'],
        countryCode: 643,
        region: 'Europe',
        region1Code: '151',
        region1: 'Eastern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Rwanda',
        alpha2: 'RW',
        alpha3: 'RWA',
        countryCode: 646,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Saint Barthélemy',
        alpha2: 'BL',
        alpha3: 'BLM',
        countryCode: 652,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Saint Helena, Ascension and Tristan da Cunha',
        alpha2: 'SH',
        alpha3: 'SHN',
        countryCode: 654,
        region: 'Africa',
        region2Code: '011',
        region2: 'Western Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Saint Kitts and Nevis',
        alpha2: 'KN',
        alpha3: 'KNA',
        countryCode: 659,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Saint Lucia',
        alpha2: 'LC',
        alpha3: 'LCA',
        countryCode: 662,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Saint Martin',
        alpha2: 'MF',
        alpha3: 'MAF',
        alternativeNames: ['Saint Martin (French part)'],
        countryCode: 663,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Saint Pierre and Miquelon',
        alpha2: 'PM',
        alpha3: 'SPM',
        countryCode: 666,
        region: 'Americas',
        region1Code: '021',
        region1: 'Northern America',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Saint Vincent and the Grenadines',
        alpha2: 'VC',
        alpha3: 'VCT',
        countryCode: 670,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Samoa',
        alpha2: 'WS',
        alpha3: 'WSM',
        countryCode: 882,
        region: 'Oceania',
        region1Code: '061',
        region1: 'Polynesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'San Marino',
        alpha2: 'SM',
        alpha3: 'SMR',
        countryCode: 674,
        region: 'Europe',
        region1Code: '039',
        region1: 'Southern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Sao Tome and Principe',
        alpha2: 'ST',
        alpha3: 'STP',
        countryCode: 678,
        region: 'Africa',
        region2Code: '017',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Saudi Arabia',
        alpha2: 'SA',
        alpha3: 'SAU',
        countryCode: 682,
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Senegal',
        alpha2: 'SN',
        alpha3: 'SEN',
        countryCode: 686,
        region: 'Africa',
        region2Code: '011',
        region2: 'Western Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Serbia',
        alpha2: 'RS',
        alpha3: 'SRB',
        countryCode: 688,
        region: 'Europe',
        region1Code: '039',
        region1: 'Southern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Seychelles',
        alpha2: 'SC',
        alpha3: 'SYC',
        countryCode: 690,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Sierra Leone',
        alpha2: 'SL',
        alpha3: 'SLE',
        countryCode: 694,
        region: 'Africa',
        region2Code: '011',
        region2: 'Western Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Singapore',
        alpha2: 'SG',
        alpha3: 'SGP',
        countryCode: 702,
        region: 'Asia',
        region1Code: '035',
        region1: 'South-eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Sint Maarten (Dutch part)',
        alpha2: 'SX',
        alpha3: 'SXM',
        countryCode: 534,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Slovakia',
        alpha2: 'SK',
        alpha3: 'SVK',
        countryCode: 703,
        region: 'Europe',
        region1Code: '151',
        region1: 'Eastern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Slovenia',
        alpha2: 'SI',
        alpha3: 'SVN',
        countryCode: 705,
        region: 'Europe',
        region1Code: '039',
        region1: 'Southern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Solomon Islands',
        alpha2: 'SB',
        alpha3: 'SLB',
        countryCode: '090',
        region: 'Oceania',
        region1Code: '039',
        region1: 'Southern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Somalia',
        alpha2: 'SO',
        alpha3: 'SOM',
        countryCode: 706,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'South Africa',
        alpha2: 'ZA',
        alpha3: 'ZAF',
        countryCode: 710,
        region: 'Africa',
        region2Code: '018',
        region2: 'Southern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'South Georgia and the South Sandwich Islands',
        alpha2: 'GS',
        alpha3: 'SGS',
        countryCode: 239,
        region: 'Americas',
        region2Code: '005',
        region2: 'South America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'South Sudan',
        alpha2: 'SS',
        alpha3: 'SSD',
        countryCode: 728,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Spain',
        alpha2: 'ES',
        alpha3: 'ESP',
        countryCode: 724,
        region: 'Europe',
        region1Code: '039',
        region1: 'Southern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Sri Lanka',
        alpha2: 'LK',
        alpha3: 'LKA',
        countryCode: 144,
        region: 'Asia',
        region1Code: '034',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Sudan',
        alpha2: 'SD',
        alpha3: 'SDN',
        countryCode: 729,
        region: 'Africa',
        region1Code: '015',
        region1: 'Northern Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Suriname',
        alpha2: 'SR',
        alpha3: 'SUR',
        countryCode: 740,
        region: 'Americas',
        region2Code: '005',
        region2: 'South America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Svalbard and Jan Mayen',
        alpha2: 'SJ',
        alpha3: 'SJM',
        countryCode: 744,
        region: 'Europe',
        region1Code: '154',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Sweden',
        alpha2: 'SE',
        alpha3: 'SWE',
        countryCode: 752,
        region: 'Europe',
        region1Code: '154',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Switzerland',
        alpha2: 'CH',
        alpha3: 'CHE',
        countryCode: 756,
        region: 'Europe',
        region1Code: '155',
        region1: 'Western Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'Syria',
        alpha2: 'SY',
        alpha3: 'SYR',
        alternativeNames: ['Syrian Arab Republic'],
        countryCode: 760,
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Taiwan',
        alpha2: 'TW',
        alpha3: 'TWN',
        alternativeNames: ['Taiwan', 'Province of China'],
        countryCode: 158,
        region: 'Asia',
        region1Code: '030',
        region1: 'Eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Tajikistan',
        alpha2: 'TJ',
        alpha3: 'TJK',
        countryCode: 762,
        region: 'Asia',
        region1Code: '143',
        region1: 'Central Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Tanzania',
        alpha2: 'TZ',
        alpha3: 'TZA',
        alternativeNames: ['United Republic of'],
        countryCode: 834,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Thailand',
        alpha2: 'TH',
        alpha3: 'THA',
        countryCode: 764,
        region: 'Asia',
        region1Code: '035',
        region1: 'South-eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Timor-Leste',
        alpha2: 'TL',
        alpha3: 'TLS',
        countryCode: 626,
        region: 'Asia',
        region1Code: '035',
        region1: 'South-eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Togo',
        alpha2: 'TG',
        alpha3: 'TGO',
        countryCode: 768,
        region: 'Africa',
        region2Code: '011',
        region2: 'Western Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continentCode: '015',
    },
    {
        name: 'Tokelau',
        alpha2: 'TK',
        alpha3: 'TKL',
        countryCode: 772,
        region: 'Oceania',
        region1Code: '061',
        region1: 'Polynesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Tonga',
        alpha2: 'TO',
        alpha3: 'TON',
        countryCode: 776,
        region: 'Oceania',
        region1Code: '061',
        region1: 'Polynesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Trinidad and Tobago',
        alpha2: 'TT',
        alpha3: 'TTO',
        countryCode: 780,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Tunisia',
        alpha2: 'TN',
        alpha3: 'TUN',
        countryCode: 788,
        region: 'Africa',
        region1Code: '015',
        region1: 'Northern Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Turkey',
        alpha2: 'TR',
        alpha3: 'TUR',
        countryCode: 792,
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Turkmenistan',
        alpha2: 'TM',
        alpha3: 'TKM',
        countryCode: 795,
        region: 'Asia',
        region1Code: '143',
        region1: 'Central Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Turks and Caicos Islands',
        alpha2: 'TC',
        alpha3: 'TCA',
        countryCode: 796,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Tuvalu',
        alpha2: 'TV',
        alpha3: 'TUV',
        countryCode: 798,
        region: 'Oceania',
        region1Code: '061',
        region1: 'Polynesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Uganda',
        alpha2: 'UG',
        alpha3: 'UGA',
        countryCode: 800,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Ukraine',
        alpha2: 'UA',
        alpha3: 'UKR',
        countryCode: 804,
        region: 'Europe',
        region1Code: '151',
        region1: 'Eastern Europe',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'UAE',
        alpha2: 'AE',
        alpha3: 'ARE',
        alternativeNames: ['United Arab Emirates'],
        countryCode: 784,
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'UK',
        alternativeNames: ['United Kingdom', 'Great Britain', 'Northern Ireland'],
        alpha2: 'GB',
        alpha3: 'GBR',
        countryCode: 826,
        region: 'Europe',
        region1Code: '154',
        continentCode: '150',
        continent: 'Europe',
    },
    {
        name: 'US',
        alternativeNames: ['United States Of America'],
        alpha2: 'US',
        alpha3: 'USA',
        countryCode: 840,
        region: 'Americas',
        region1Code: '021',
        region1: 'Northern America',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'United States Minor Outlying Islands',
        alpha2: 'UM',
        alpha3: 'UMI',
        countryCode: 581,
        region: 'Oceania',
        region1Code: '057',
        region1: 'Micronesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Uruguay',
        alpha2: 'UY',
        alpha3: 'URY',
        countryCode: 858,
        region: 'Americas',
        region2Code: '005',
        region2: 'South America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Uzbekistan',
        alpha2: 'UZ',
        alpha3: 'UZB',
        countryCode: 860,
        region: 'Asia',
        region1Code: '143',
        region1: 'Central Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Vanuatu',
        alpha2: 'VU',
        alpha3: 'VUT',
        countryCode: 548,
        region: 'Oceania',
        region1Code: '054',
        region1: 'Melanesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Venezuela',
        alpha2: 'VE',
        alpha3: 'VEN',
        alternativeNames: ['Bolivarian Republic of'],
        countryCode: 862,
        region: 'Americas',
        region2Code: '005',
        region2: 'South America',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Vietnam',
        alpha2: 'VN',
        alpha3: 'VNM',
        alternativeNames: ['Viet Nam'],
        countryCode: 704,
        region: 'Asia',
        region1Code: '035',
        region1: 'South-eastern Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Virgin Islands (British)',
        alpha2: 'VG',
        alpha3: 'VGB',
        countryCode: '092',
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Virgin Islands (U.S.)',
        alpha2: 'VI',
        alpha3: 'VIR',
        countryCode: 850,
        region: 'Americas',
        region2Code: '029',
        region2: 'Caribbean',
        region1Code: '419',
        region1: 'Latin America and the Caribbean',
        continentCode: '019',
        continent: 'Americas',
    },
    {
        name: 'Wallis and Futuna',
        alpha2: 'WF',
        alpha3: 'WLF',
        countryCode: 876,
        region: 'Oceania',
        region1Code: '061',
        region1: 'Polynesia',
        continentCode: '009',
        continent: 'Oceania',
    },
    {
        name: 'Western Sahara',
        alpha2: 'EH',
        alpha3: 'ESH',
        countryCode: 732,
        region: 'Africa',
        region1Code: '015',
        region1: 'Northern Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Yemen',
        alpha2: 'YE',
        alpha3: 'YEM',
        countryCode: 887,
        region: 'Asia',
        region1Code: '145',
        region1: 'Western Asia',
        continentCode: '142',
        continent: 'Asia',
    },
    {
        name: 'Zambia',
        alpha2: 'ZM',
        alpha3: 'ZMB',
        countryCode: 894,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
    {
        name: 'Zimbabwe',
        alpha2: 'ZW',
        alpha3: 'ZWE',
        countryCode: 716,
        region: 'Africa',
        region2Code: '014',
        region2: 'Eastern Africa',
        region1Code: '202',
        region1: 'Sub-Saharan Africa',
        continent: 'Africa',
        continentCode: '002',
    },
];

const getCountryName = (country_code) => {
    return countries.find(
        (country) => country.alpha2 === country_code || country.alpha3 === country_code,
    )?.name;
};

const getCountryShortCode = (country_code) => {
    if (country_code && country_code.length === 3) {
        return countries.find((country) => country.alpha3 === country_code)?.alpha2;
    } else {
        return country_code;
    }
};

const getCountryCodeLong = (country_code) => {
    return countries.find((country) => country.alpha2 === country_code)?.alpha3;
};

const getCountryCodeByName = (name) => {
    return countries.find((country) => country.name === name)?.alpha3;
};

export {
    continents,
    countries,
    regions1,
    regions2,
    getCountryName,
    getCountryShortCode,
    getCountryCodeLong,
    getCountryCodeByName,
};